default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: 729774872b394cada5963537774c6d97
  pool: 5
  username:729774872b394cada5963537774c6d97
  password:Russel19891212
  host: mysql-2.mc.lolipop.lan

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: 729774872b394cada5963537774c6d97
  pool: 5
  username:729774872b394cada5963537774c6d97
  password:Russel19891212
  host: mysql-2.mc.lolipop.lan