default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
    <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USERNAAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  master_key: <%= ENV['RAILS_MASTER_KEY'] %>